#define Was_ist_der_MIS_Report_Designer	1
#define Erste_Schritte	2
#define Voraussetzungen	3
#define Reportaufruf	4
#define MIS_Reporte	5
#define Begriffsdefinitionen	6
#define Dimensionen_im_MIS_Report	7
#define Ausprägungen	8
#define Maßzahlen	9
#define Würfel	10
#define Multidimensionale_Auswertung	11
#define Hierarchien	12
#define Weitere_Begriffe	13
#define Umsetzung_der_MIS_Reporte_in_Excel_Pivot_Tabellen	14
#define Die_Elemente_der_Pivot_Tabelle_im_MIS_Report	15
#define Dimensionen	16
#define Das_Seitenfeld_Pagefield	17
#define Zeilen_Spalten_und_Maßzahlen	18
#define PivotTable_Symbolleiste	19
#define Bericht_formatieren_...	20
#define PivotChart	21
#define Detail_ausblenden_Detail_einblenden	22
#define Feldeigenschaften	23
#define Felder_ausblenden_Felder_anzeigen	24
#define Bekannte_Einschränkungen	25
#define Einschränkungen_für_mehrdimensionale_Reporte	26
#define Spaltenfelder	27
#define Zeilenfelder	28
#define Maximale_Anzahl_an_Datensätzen	29
#define Elemente_pro_Feld	30
#define Einschränkungen_für_vordefinierte_Reporte	31
#define Benutzerdefinierte_Reporte	32
#define Beispiel_Transaktionen_pro_Operator	33
#define Beispiel_berpr_fung_der_Dienstg_te	34
#define Beispiel_Transaktionen_pro_Zieldatenbank	35
#define Funktionen	36
#define Öffnen_eines_MIS_Reports	37
#define Registerkarte_Datenbank	38
#define Registerkarte_Reportzeitraum	39
#define Optionale_Registerkarten	40
#define Hinzufügen_eines_benutzerdefinierten_Reports_zum_MIS_Menü	41
#define Entfernen_eines_benutzerdefinierten_Reports_vom_MIS_Menü	42
#define Austausch_von_Reporten_mit_anderen_Benutzern	43
#define Hinzufügen_Entfernen_von_Aufträgen_zum_automatischen_Erstellen_eines_Reports_optional	44
#define Auftrag_zum_automatischen_Erstellen_eines_Reports_hinzufügen	45
#define Auftrag_zum_automatischen_Erstellen_eines_Reports_modifizieren	46
#define Auftrag_zum_automatischen_Erstellen_eines_Reports_entfernen	47
#define Allgemeine_Tipps	48
#define Das_MIS_Menü_ist_in_Excel_nicht_zu_finden	49
#define Der_MIS_Report_Designer_meldet_dass_keine_DB2_Datenbank_vorhanden_ist.	50
#define Der_Auftrag_zum_automatischen_Erstellen_eines_Reports_wurde_nicht_ausgeführt.	51
#define Hinweise_und_Fehlermeldungen_beim_Start_des_MIS_Report_Designer	52
#define MIS_Add_In_Initialisierung_fehlgeschlagen	53
#define MIS_Fehlende_MS_Office_Komponente	54
#define Hinweise_und_Fehlermeldungen_beim_Öffnen_von_Reporten	55
#define MIS_Report_kann_nicht_geöffnet_werden	56
#define MIS_Neue_Anmeldung	57
#define MIS_Daten_wurden_nicht_gefunden	58
#define MIS_Kann_Report_nicht_erstellen	59
#define MIS_Daten_konnten_nicht_geladen_werden	60
#define MIS_Bitte_überprüfen_Sie_Ihre_Angaben1	61
#define MIS_DB2_Datenbank_nicht_gefunden	62
#define MIS_Leerer_Report	63
#define MIS_Fehler_bei_Verbindungsaufbau_zu_...	64
#define MIS_Fehler_beim_Laden_der_Daten_aus_der_DB2_Datenbank	65
#define MIS_Fehler_beim_Festlegen_des_Reportzeitraums_in_der_DB2_Datenbank	66
#define Hinweise_und_Fehlermeldungen_beim_Hinzufügen_und_Entfernen_von_benutzerdefinierten_Reporten	67
#define MIS_Menüeintrag_existiert_schon	68
#define MIS_Kann_Report_nicht_hinzufügen	69
#define MIS_Reporte_löschen	70
#define MIS_Speichern_fehlgeschlagen	71
#define MIS_Datei_schon_vorhanden	72
#define Hinweise_und_Fehlermeldungen_beim_Aufruf_des_Dialogs_Aufträge	73
#define MIS_Reporte_nicht_gefunden	74
#define Status_Zeitplandienst_gestoppt	75
#define Status_Zeitplandienst_angehalten	76
#define Fehler_bei_der_Status_Abfrage_des_Zeitplandienstes1.	77
#define Hinweise_und_Fehlermeldungen_beim_Hinzufügen_oder_Entfernen_von_Aufträgen	78
#define MIS_Report_auswählen	79
#define MIS_Bitte_überprüfen_Sie_Ihre_Angaben2	80
#define MIS_Bitte_überprüfen_Sie_Ihre_Angaben3	81
#define MIS_Falscher_Zeitbereich	82
#define MIS_Startzeitpunkt_falsch	83
#define MIS_Kein_Kennwort	84
#define MIS_Kennworteingabe_falsch	85
#define MIS_Parameter_undefiniert	86
#define MIS_Auftrag_konnte_nicht_erstellt_werden	87
#define MIS_Kein_Auftrag_ausgewählt	88
#define MIS_Auftrag_löschen	89
#define Allgemeine_Hinweise_und_Fehlermeldungen	90
#define MIS_Programm_beendet	91
#define Gl_API	92
#define Gl_DA	93
#define Gl_EDA	94
#define Gl_E.115	95
#define Gl_ID	96
#define Gl_IDIS	97
#define Gl_IDW	98
#define Gl_ITG	99
#define Gl_LDAP	100
#define Gl_MIS	101
#define Gl_NDIS	102
#define Gl_OSA	103
#define Gl_OSA_API	104
#define Gl_OSA_Gateway	105
#define Gl_OTG	106
#define Gl_QST	107
#define Gl_SES	108
#define Gl_TDF	109
#define Gl_TDS	110

