#define What_is_the_MIS_Report_Designer	1
#define First_steps	2
#define Preconditions	3
#define Creating_a_report	4
#define Saving_a_report_with_data	5
#define MIS_reports	6
#define Definition_of_terms	7
#define Dimensions_in_MIS_reports	8
#define Members	9
#define Measures	10
#define Cubes	11
#define Multidimensional_evaluation	12
#define Hierarchies	13
#define List_reports	14
#define Other_terms	15
#define Conversion_of_the_MIS_Reports_into_Excel_pivot_tables	16
#define Elements_of_the_pivot_table_in_the_MIS_report	17
#define Dimensions	18
#define Page_field	19
#define Rows_columns_and_measures	20
#define PivotTable_toolbar	21
#define Format_Report_	22
#define PivotChart	23
#define Hide_Detail_Show_Detail	24
#define Field_Settings	25
#define Hide_Fields_Display_Fields	26
#define Restrictions	27
#define Restrictions_for_multidimensional_reports	28
#define Column_fields	29
#define Row_fields	30
#define Maximum_number_of_records	31
#define Items_per_field	32
#define Restrictions_for_list_reports	33
#define Customized_reports	34
#define Example_Operator_performance	35
#define Example_Service_level_verification	36
#define Example_Target_database_level_verification	37
#define Functions	38
#define Open_an_MIS_report	39
#define _Data_Source_tab_page	40
#define _Time_Range_tab_page	41
#define Optional_tab_pages	42
#define Add_a_customized_report_to_the_MIS_menu	43
#define Remove_a_customized_report_from_the_MIS_menu	44
#define Exchange_reports_with_other_users	45
#define Add_remove_scheduled_tasks_to_automatically_create_a_report_optional	46
#define Add_scheduled_task_to_automatically_create_a_report	47
#define Modify_scheduled_task	48
#define Remove_scheduled_task_to_automatically_create_a_report	49
#define Troubleshooting	50
#define General_tips	51
#define The_MIS_menu_cannot_be_found_in_Excel	52
#define The_MIS_Report_Designer_sends_a_message_that_no_DB2_database_is_available.	53
#define The_scheduled_task_to_automatically_create_a_report_was_not_executed.	54
#define Hints_and_error_messages_during_startup_of_the_MIS_Report_Designer	55
#define MIS_Add_in_initialization_failed	56
#define MIS_Missing_MS_Office_Component	57
#define Hints_and_error_messages_while_reports_are_opened	58
#define MIS_Can_t_open_report	59
#define MIS_Change_logon	60
#define MIS_Data_not_found_in_database	61
#define MIS_Can_t_get_data	62
#define MIS_Can_t_load_data	63
#define MIS_Please_check_your_input1	64
#define MIS_DB2_database_not_found	65
#define MIS_Empty_report	66
#define MIS_Error_connecting_to_...	67
#define MIS_Error_while_getting_data_from_the_DB2_database	68
#define MIS_Error_while_setting_time_range_in_DB2_database	69
#define Hints_and_error_messages_during_adding_and_removing_customized_reports	70
#define MIS_Menu_name_already_exists	71
#define MIS_Can_t_add_report	72
#define MIS_Delete_reports	73
#define MIS_Save_report_failed	74
#define MIS_File_exists	75
#define Hints_and_error_messages_during_startup_of_the_dialog_Schedule	76
#define MIS_No_report_entry_found	77
#define Status_Schedule_service_Stopped	78
#define Status_Schedule_service_Paused	79
#define Error_while_getting_the_status_of_the_Schedule_service1	80
#define Hints_and_error_messages_during_adding_and_removing_scheduled_tasks	81
#define MIS_Select_report	82
#define MIS_Please_check_your_input2	83
#define MIS_Please_check_your_input3	84
#define MIS_Wrong_time_range	85
#define MIS_Task_is_not_created	86
#define MIS_No_password	87
#define MIS_Wrong_password	88
#define MIS_Scheduler_setting_couldn_t_be_determined	89
#define MIS_No_scheduled_task_selected	90
#define MIS_Delete_scheduled_task	91
#define General_hints_and_error_messages	92
#define MIS_Program_stopped	93
#define Gl_API	94
#define Gl_DA	95
#define Gl_EDA	96
#define Gl_ID	97
#define Gl_IDIS	98
#define Gl_IDW	99
#define Gl_ITG	100
#define Gl_LDAP	101
#define Gl_MIS	102
#define Gl_NDIS	103
#define Gl_OSA	104
#define Gl_OSA_API	105
#define Gl_OTG	106
#define Gl_QST	107
#define Gl_SES	108
#define Gl_TDF	109
#define Gl_TDS	110
